# src/Ens/SitesBundle/Resources/config/doctrine/User.orm.yml
 
Ens\SitesBundle\Entity\User:
  type: entity
  table: user
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    username:
      type: string
      length: 255
    password:
      type: string
      length: 255