<?php
namespace Ens\SitesBundle\Repository;

use Doctrine\ORM\EntityRepository;
/**
 * JobRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactRepository extends EntityRepository
{

}