<?php
namespace Ens\SitesBundle\Repository;

use Doctrine\ORM\EntityRepository;
/**
 * JobRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PagesRepository extends EntityRepository
{
	public function getMenu()
	{
	  $qb = $this->createQueryBuilder('j')
	    ->where('j.menu = 1');
	 

	  $query = $qb->getQuery();
	 
	  return $query->getResult();
	}

	/*public function getPage($title)
	{
	  $qb = $this->createQueryBuilder('j')
	    ->where('j.title = :title')
	    ->setParameter('title', $title);;
	 

	  $query = $qb->getQuery();
	 
	  return $query->getResult();
	}*/
}